### ISSUE TITLE
Missing Element.children

### ISSUE THREAD

**Issue by CGJennings** [google/elemental2#33] opened 2018-02-06 18:55 UTC
The `Element` class should have a `children` property returning an `HTMLCollection<Element>`. This is specified by the `ParentNode` mixin. (The same mixin also specifies `firstElementChild`, `lastElementChild`, and `childElementCount`, all of which are present.)

**Comment by CGJennings** [comment] 2018-02-12 17:33
I see that `Element.parentElement` is also missing.

Are reports of this nature useful, or is this something that should sort itself out when the tool is run against newer/different W3C spec data?

**Comment by tbroyer** [comment] 2018-02-12 17:43
Elemental2 is generated from closure-compiler externs files, not "W3C spec data" (see also https://github.com/google/elemental2/blob/master/CONTRIBUTING.md#contributing-a-patch)

`children` is defined in https://github.com/google/closure-compiler/blob/d1c1673d1d891616144f1f5d0d9642dd1e232612/externs/browser/gecko_dom.js#L737-L741, `firstElementChild` et al. are defined in https://github.com/google/closure-compiler/blob/55cf43ee31e80d89d7087af65b5542aa63987874/externs/browser/w3c_elementtraversal.js, and `parentElement` is defined in https://github.com/google/closure-compiler/blob/55cf43ee31e80d89d7087af65b5542aa63987874/externs/browser/w3c_elementtraversal.js

Per https://github.com/google/elemental2/blob/e6944c3cdb6b637822edcc9d76f70ce8cb3b4424/java/elemental2/dom/BUILD#L14-L23, those would need to be added to this repo's `w3c_dom2.js.diff` though.

So I do think those reports are useful yes :wink:

**Comment by CGJennings** [comment] 2018-02-12 18:45
Good to know.

(I do get that right now the defs are based off Closure. By "spec data" I simply meant to include any possible future data sources, whether Closure, IDL, `.d.ts` or whatever else. Sorry for any confusion.)

**Comment by niloc132** [comment] 2018-07-15 01:43
@tbroyer I think you have a copy/paste error, parentElement can't be found in that file (or its history). Instead, it can be found in https://github.com/google/closure-compiler/blob/0b04093/externs/browser/ie_dom.js

**Comment by jDramaix** [comment] 2019-03-12 00:50
This will be fixed with #86 #87

**Closed by jDramaix** 2019-03-12 00:50 UTC
Labels: Extern files cleanup

**Comment by realityforge** [comment] 2019-03-19 23:03
Element.parentElement will be made available once the https://github.com/google/closure-compiler/pull/3273 PR lands.

**Comment by realityforge** [comment] 2019-03-19 23:13
childElementCount is made into an integer via https://github.com/google/elemental2/pull/98

**Comment by realityforge** [comment] 2019-03-19 23:25
Element.children will be correctly typed after https://github.com/google/closure-compiler/pull/3275 lands but it will not be included in Elemental until #86 lands ... or alternatively a new `whatwg_dom_ls.js` is added.

**Comment by jDramaix** [comment] 2020-11-02 17:56
It has been closed as duplicate of #86 that are still open
