### ISSUE TITLE
URL definition is missing

### ISSUE THREAD

**Issue by BenDol** [google/elemental2#56] opened 2018-06-18 13:05 UTC
https://developer.mozilla.org/en-US/docs/Web/API/URL

**Comment by gkdn** [comment] 2018-06-19 02:01
url.js is missing in elemental2 extern input.

**Comment by niloc132** [comment] 2018-06-19 14:01
It looks like the .diff removes it, but I'm not clear why - the commit message which includes the diff removing it is the initial commit, and there are many other types removed there as well. 

Any obvious objections to trying to restore that and other fileapi types?

**Comment by tbroyer** [comment] 2018-07-05 17:00
Fwiw, this is actually a duplicate of #1. No need to close this one in favor of reopening the other, just noting here the relationship between both issues.

**Comment by jDramaix** [comment] 2019-03-12 05:36
Will be fixed by fixing #89

**Closed by jDramaix** 2019-03-12 05:36 UTC
