### ISSUE TITLE
elemental2.dom.HTMLDocument  missing defaultView and elemental2.dom.Window missing getComputedStyle

### ISSUE THREAD

**Issue by dfht** [google/elemental2#61] opened 2018-09-11 16:53 UTC
For example, I wanted to do this (JSNI  JavaScript) in Elemental 2:
`var zindex = document.defaultView.getComputedStyle(elems[i],null).getPropertyValue("z-index");`

	

But I could not find defaultView on Document or HTMLDocument, and could not find getComputedStyle except on ViewCSS (it seems it should be on Window).
What is ViewCSS and how do I achieve what I want here in Elemental 2? It seems it is not currently possible, and that my JSNI must stay for now.......

**Comment by niloc132** [comment] 2018-09-11 19:04
From https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle, it looks like you don't need to say `document.defaultView` but just `window` (and actually both of those are wrong in JSNI, it should be `$doc.defaultView` and `$wnd` respectively). 

To achieve the same thing in jsinterop with Elemental2, try this:

    String zIndex = ((ViewCSS) DomGlobal.window).getComputedStyle(elems[i]).getPropertyValue("z-index");

**Comment by dfht** [comment] 2018-09-12 07:34
I'm pretty sure I tried casting window to ViewCSS, but got an error (the usual class cast kind of error one gets in GWT occasionally). However, I will try again. In general though, it seems like guesswork to know what you need in a case like this, and some decent documentation would be great. Also, the double cast to Object then to what you actually want (when converting between elemental elements and 'traditional' GWT ones) is somewhat ugly and error prone, and somewhat undermines the utility of having type checked JavaScript. However I expect a more elegant approach will surface eventually...
Regarding the JSNI, it may have been wrong , but it did seem to work..... Why is it always $doc instead of document in JSNI? I've never quite understood that...
Thanks for your help and suggestion.

**Comment by dfht** [comment] 2018-09-12 09:35
Ah, I guess the generics trick in  Js.cast avoids the double cast. A bit neater at least..

I tried your suggestion, but I get a ClassCastException below when casting to defaultView:

` Window window = DomGlobal.window;`
`ViewCSS defaultView = Js.cast(window);`


I'm using GWT 2.8.1 and Elemental 2 1.0.0-RC1.
Do you think upgrading to GWT 2.8.2 would help here?

**Comment by dfht** [comment] 2018-09-12 09:50
In more detail, when debugging in Chrome, in the castToNative check, the passed in jsType when checking the cast is null, which is what leads to the ClassCastException. Do you have any idea why this might be?

`/**
   * A dynamic cast that optionally checks for JsType prototypes.
   */
  static Object castToNative(Object src, JavaScriptObject jsType) {
    checkType(src == null ||  jsinstanceOf(src, jsType));
    return src;
  }`


`/**
   * Determine if object is an instanceof jsType regardless of window or frame.
   */
  @HasNoSideEffects
  private static native boolean jsinstanceOf(Object obj, JavaScriptObject jsType) /*-{
    return obj && jsType && obj instanceof jsType;
  }-*/;
`

**Comment by dfht** [comment] 2018-09-12 10:11
And if I change from:
`ViewCSS defaultView = Js.<ViewCSS>cast(window);`
to
 `ViewCSS defaultView = Js.<ViewCSS>uncheckedCast(window);`

then it all works, as it avoids the cast check!

I'm guessing there is a bug in here somewhere......

**Comment by niloc132** [comment] 2018-09-12 11:37
Yes, I didn't actually run the code, thanks for the double check. The issue is that according to the spec, `ViewCSS` is an interface, but https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_css.js#L912 shows that closure externs define it as a class, which breaks when you attempt to cast as you observed (interfaces "don't really exist" in JS, they just describe a consistent set of methods/etc).

Until closure (and elemental2) are updated (probably to include `@interface`?), you'll need that uncheckedCast call.

**Comment by dfht** [comment] 2018-09-12 17:47
Thanks again - Even with the unchecked cast, I still prefer using Elemental 2/ JSInterop and having some type checking to having none (with JSNI) here, so it's good for now.

**Comment by jDramaix** [comment] 2019-03-12 00:23
**Contribution is welcome here.**

As @niloc132 suggested, this can be easily fixed by fixing the [extern file](https://github.com/google/closure-compiler/blob/master/externs/browser/w3c_css.js#L912) and turn CssView to an interface (by replacing `@constructor` to `@interface`)

`document.defaultView` will be solved with #86

**Comment by realityforge** [comment] 2019-05-21 06:35
The update to the `ViewCSS` type has been submitted as google/closure-compiler#3392

**Comment by realityforge** [comment] 2019-05-25 02:15
Fix applied upstream so this can be closed

**Comment by jDramaix** [comment] 2019-05-28 18:38
Thanks!

**Closed by jDramaix** 2019-05-28 18:38 UTC
Labels: Extern files cleanup, good first issue, help wanted
